//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Bai_login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUSer
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Username can not be null.")]
        public string username { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password can not be null.")]
        public string password { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
